service: freely-homework

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  environment:
    USERS_TABLE_NAME: users
    USER_TABLE_INDEX: email-index
    SNS_TOPIC: !Ref UserRegistrationTopic
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !Sub "${UsersTable.Arn}/index/*"

        - Effect: Allow
          Action:
            - sns:Publish
            - sns:Subscribe
            - sns:Receive
          Resource: !Ref UserRegistrationTopic

        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*

functions:
  userRegister:
    handler: src/handlers/userHandler.userRegister
    events:
      - http:
          path: user/register
          method: post
          cors:
            origin: "*"
            methods: POST
  
  getUserByEmail:
    handler: src/handlers/userHandler.getUserByEmail
    events:
      - http:
          path: user/email/{email}
          method: get
          cors:
            origin: "*"
            methods: GET

  deleteUserById:
    handler: src/handlers/userHandler.deleteUserById
    events:
      - http:
          path: user/{id}
          method: delete
          cors:
            origin: "*"
            methods: DELETE

  handleUserRegistration:
    handler: src/handlers/userNotificationHandler.handleUserRegistration
    events:
      - sns:
          arn: !Ref UserRegistrationTopic
          topicName: user-registration-topic

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    
    UserRegistrationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: user-registration-topic
        DisplayName: User Registration Notifications