service: freely-homework

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  environment:
    USERS_TABLE_NAME: users
    USER_TABLE_INDEX: email-index
    MESSAGES_TABLE_NAME: messages
    SNS_TOPIC: !Ref UserRegistrationTopic
    CREATE_MESSAGE_QUEUE_URL: !Ref CreateMessageQueue

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !Sub "${UsersTable.Arn}/index/*"
            - !GetAtt MessagesTable.Arn

        - Effect: Allow
          Action:
            - sns:Publish
            - sns:Subscribe
            - sns:Receive
          Resource: !Ref UserRegistrationTopic

        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:SendMessageBatch
            - sqs:ReceiveMessage
            - sqs:GetQueueUrl
          Resource: !GetAtt CreateMessageQueue.Arn

        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*

functions:
  userRegister:
    handler: src/handlers/userHandler.userRegister
    events:
      - http:
          path: user/register
          method: post
          cors:
            origin: "*"
            methods: POST
  
  getUserByEmail:
    handler: src/handlers/userHandler.getUserByEmail
    events:
      - http:
          path: user/email/{email}
          method: get
          cors:
            origin: "*"
            methods: GET

  deleteUserById:
    handler: src/handlers/userHandler.deleteUserById
    events:
      - http:
          path: user/{id}
          method: delete
          cors:
            origin: "*"
            methods: DELETE

  handleUserRegistration:
    handler: src/handlers/userNotificationHandler.handleUserRegistration
    events:
      - sns:
          arn: !Ref UserRegistrationTopic
          topicName: user-registration-topic

  handleCreateMessage:
    handler: src/handlers/queueHandler.handleCreateMessage
    events:
      - sqs:
          arn: !GetAtt CreateMessageQueue.Arn
          batchSize: 3

  createMessage:
    handler: src/handlers/messageHandler.createMessage
    events:
      - http:
          path: /message/create
          method: post
          cors:
            origin: "*"
            methods: POST

  listMessages:
    handler: src/handlers/messageHandler.listMessages
    events:
      - http:
          path: /message/list
          method: get
          cors:
            origin: "*"
            methods: GET

  deleteMessage:
    handler: src/handlers/messageHandler.deleteMessage
    events:
      - http:
          path: /message/delete/{id}
          method: delete
          cors:
            origin: "*"
            methods: DELETE

  postMessage:
    handler: src/handlers/messageHandler.postMessage
    events:
      - http:
          path: /message/post
          method: post
          cors:
            origin: "*"
            methods: POST

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MESSAGES_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    
    UserRegistrationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: user-registration-topic
        DisplayName: User Registration Notifications

    CreateMessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: create-message-queue
